[package]
name = "rtos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["cortex-m7"]
std = []
cortex-m7 = []

[dependencies]
